base_model:
  IMAGE_SIZE: [224, 224, 3] # As per VGG 16 model
  INCLUDE_TOP: False
  CLASSES: 4
  WEIGHTS: imagenet
  LEARNING_RATE: 0.01

model_training:
  AUGMENTATION: True
  IMAGE_SIZE: [224, 224, 3] # As per VGG 16 model
  BATCH_SIZE: 16
  EPOCHS: 5
  LEARNING_RATE: 0.01
  OPTIMIZER: "Adam"
  CHECKPOINT: True
  MLFLOW_TRACKING: True
  AUGMENTATION_PARAMS:
    rotation_range: 15
    width_shift_range: 0.1
    height_shift_range: 0.1
    shear_range: 0.1
    zoom_range: 0.2
    horizontal_flip: true
    fill_mode: "nearest"

predictions:
  IMAGE_SIZE: [224, 224, 3] # As per VGG 16 model
  NORMALIZATION: 255.0

model_selector:
  FILENAME_REGEX: "model_e\\d+_acc[\\d.]+_vacc([\\d.]+)\\.keras"
  