stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    output:
      - artifacts/data_ingestion/Data

  base_model:
    cmd: python src/cnnClassifier/pipeline/stage_02_base_model.py
    deps:
      - src/cnnClassifier/pipeline/stage_02_base_model.py
      - config/config.yaml
      - params/params.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    output:
      - artifacts/base_model
      