artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion/data
  kaggle_dataset: "mohamedhanyyy/chest-ctscan-images"
  download_zip: artifacts/data_ingestion/data/chest-ctscan-images.zip
  extracted_file: artifacts/data_ingestion/data/Data

