artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  kaggle_dataset: "mohamedhanyyy/chest-ctscan-images"
  download_zip: artifacts/data_ingestion/chest-ctscan-images.zip
  extracted_file: artifacts/data_ingestion/Data
  rename_map_yaml: config/class_name_map.yaml

base_model:
  root_dir: artifacts/base_model
  model_path: artifacts/base_model/base_model.keras
  updated_model_path: artifacts/base_model/updated_base_model.keras

model_training:
  root_dir: artifacts/model_training
  trained_model_path: artifacts/model_training
  updated_model_path: artifacts/base_model/updated_base_model.keras
  training_dataset: artifacts/data_ingestion/Data/train
  validation_dataset: artifacts/data_ingestion/Data/valid

hyperparameter_search:
  root_dir: artifacts/hyperparameter_search

predictions:
  model: artifacts/model_training/trained_model_20250708_0949.keras
  class_indices: artifacts/model_training/class_indices.json
