artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  kaggle_dataset: "mohamedhanyyy/chest-ctscan-images"
  download_zip: cartifacts/data_ingestion/chest-ctscan-images.zip
  extracted_file: artifacts/data_ingestion